developer: Brightside Tech
developerUrl: "https://brightsidetech.io"
url: https://www.bgcofcv.org
#url: https://development.bgcofcv.org
markdown: kramdown
destination: dist
source: root/jekyll
include:
    - _pages
plugins:
    - jemoji
    - jekyll-sitemap
future: true
collections:
    our-clubs:
        output: true
    program-categories:
        output: true
    events:
        output: true
    campaigns:
        output: false
