developer: Brightside Tech
developerUrl: "#"
#url: https://bgcofcv.netlify.com/
markdown: kramdown
destination: dist
source: root/jekyll
include:
    - _pages
plugins:
    - jemoji
    - jekyll-sitemap
future: true
collections:
    our-clubs:
        output: true
    program-categories:
        output: true
    events:
        output: true
