port: 4001
timezone: America/Los_Angeles
developer: Brightside Tech
developerUrl: "https://godiego.me"
markdown: kramdown
destination: dist
source: root/jekyll
include:
  - _pages
  - _dev_admin
exclude:
  - admin
  - _pages/virtual-club
plugins:
  - jemoji
  - jekyll-sitemap
future: true
collections:
  our-clubs:
    output: true
  program-categories:
    output: true
  events:
    output: true
  campaigns:
    output: false
