timezone: America/Los_Angeles
env: DEVELOPMENT
developer: Brightside Tech
developerUrl: "https://brightsidetech.io"
url: https://development.bgcofcv.org
markdown: kramdown
destination: dist
source: root/jekyll
include:
    - _pages
    - _dev_admin
exclude:
    - admin
plugins:
    - jemoji
    - jekyll-sitemap
future: true
collections:
    our-clubs:
        output: true
    program-categories:
        output: true
    events:
        output: true
    campaigns:
        output: false
