backend:
    name: git-gateway
    branch: cms
    repo: Brightside-Technologies/bgcofcv
accepted_roles:
    - Administrator
    - Editor
display_url: "https://bgcofcv.netlify.com/"
logo_url: https://bgcofcv.netlify.com/assets/images/hero-logo.png
media_folder: root/src/assets/images
public_folder: assets/images
collections:
    - name: metadata
      label: "Site Metadata"
      delete: false
      description: "Site metadata and global settings"
      extension: json
      files:
          - editor:
                preview: false
            file: root/jekyll/_data/metadata.json
            label: "Site Metadata"
            name: metadata
            fields:
                - label: "Site Title"
                  name: title
                  widget: string
                - label: Favicon
                  name: favicon
                  required: false
                  widget: image
                - default: website
                  label: "Site Type"
                  name: type
                  widget: string
                - label: "Site Description"
                  name: description
                  widget: text
                - label: "Site Thumbnail"
                  name: image
                  required: false
                  widget: image
                - label: "Site Url"
                  name: url
                  required: false
                  widget: string
                - label: "Facebook Url"
                  name: facebookUrl
                  required: false
                  widget: string
                - label: "Twitter Url"
                  name: twitterUrl
                  required: false
                  widget: string
                - label: "Twitter Username"
                  name: twitterUsername
                  required: false
                  widget: string
                - label: "Contact Email"
                  name: email
                  required: false
                  widget: string
                - label: "Contact Phone Number"
                  name: phone
                  required: false
                  widget: string
                - label: "Google Analytics ID"
                  name: googleAnalyticsId
                  required: false
                  widget: string
                - allow_add: true
                  label: "Site Keywords (for SEO)"
                  name: keywords
                  widget: list

    - name: events
      label: Events
      folder: root/jekyll/_events
      extension: html
      create: true
      delete: true
      description: Add, edit, and delete Events
      slug: "{{slug}}"
      fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "events-layout" }
          - { label: "Title", name: "title", widget: "string", tagname: "h1" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Image", name: "image", widget: "image", required: false, tagname: "" }
          - { label: "Date", name: "date", widget: "datetime", required: true, timeFormat: false }
          - label: Contact
            name: contact
            widget: object
            fields:
                - { label: "Name", name: "name", widget: "string" }
                - { label: "Title", name: "title", widget: "string" }
                - { label: "Email", name: "email", widget: "string" }
                - label: Phone
                  name: phone
                  widget: object
                  fields:
                      - { label: Number, name: number, widget: "string" }
                      - { label: Extension, name: extension, widget: "string" }
                - label: Event Time
                  name: time
                  widget: object
                  fields:
                      - {
                            label: Start Time,
                            name: startTime,
                            widget: datetime,
                            dateFormat: false,
                            timeFormat: "hh:mm a",
                            format: "hh:mm a",
                        }
                      - {
                            label: End Time,
                            name: endTime,
                            widget: datetime,
                            dateFormat: false,
                            timeFormat: "hh:mm a",
                            default: null,
                            format: "hh:mm a",
                        }

    - name: partners
      label: Partners
      delete: true
      description: Manage organization partners/donors
      extension: json
      files:
          - label: Partners
            name: partners
            file: root/jekyll/_data/partners.json
            editor:
                preview: false
            fields:
                - name: partners
                  label: Partners
                  widget: list
                  fields:
                      - { label: Partner Name, name: name, widget: string }
                      - { label: Logo, name: logo, widget: image }
                      - { label: Back-link url, name: url, widget: string }

    - name: team
      label: Team
      delete: true
      description: Manage staff and board members
      extension: json
      files:
          - label: Adminastrative Staff
            name: staff
            file: root/jekyll/_data/staff.json
            editor:
                preview: false
            fields:
                - name: staff
                  label: Staff
                  widget: list
                  fields:
                      - { label: Name, name: name, widget: string }
                      - { label: Title, name: title, widget: string }
                      - { label: Email, name: email, widget: string }
                      - label: Phone
                        name: phone
                        widget: object
                        fields:
                            - { label: Number, name: number, widget: string }
                            - { label: Extension, name: extension, widget: string }
          - label: Board Members
            name: board-members
            file: root/jekyll/_data/board-members.json
            editor:
                preview: false
            fields:
                - name: board-members
                  label: Board Members
                  widget: list
                  fields:
                      - { label: Name, name: name, widget: string }
                      - { label: Title, name: title, widget: string }
          - label: Friends of Board
            name: friends
            file: root/jekyll/_data/friends-of-board.json
            editor:
                preview: false
            fields:
                - name: friends
                  label: Friends of Board
                  widget: list
                  fields:
                      - { label: Name, name: name, widget: string }
                      - { label: Title, name: title, widget: string }
          - label: Emeritus
            name: emeritus
            file: root/jekyll/_data/emeritus-members.json
            editor:
                preview: false
            fields:
                - name: emeritus
                  label: Emeritus
                  widget: list
                  fields:
                      - { label: Name, name: name, widget: string }
                      - { label: Title, name: title, widget: string }
